//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by laserMachine.rc
//
#define ID_EDIT_FEEDRATE_OVERRIDE       4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MONITOR                     101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_MACHINE_STATUS     120
#define ID_STATUSBAR_MOUSE_POSITION     121
#define IDS_STATUS_PANE1                122
#define IDS_MOUSE_POSITION              122
#define IDS_STATUS_PANE2                123
#define IDS_MACHINE_STATUS              123
#define IDS_AXES_POSITION               124
#define IDS_OPERATE_MODE                125
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_laserMachineTYPE            130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_OUTPUT_WND                  157
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_OUTPUT_POPUP                182
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_BUILD_TAB                   300
#define IDS_PROGRAM_TAB                 300
#define IDS_DEBUG_TAB                   301
#define IDS_ALARM_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_LOG_ALARM                   302
#define IDS_LOG_TAB                     302
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDS_MACHINE_STATUS_STANDBY      307
#define ID_STATUSBAR_AXES_POSITION      310
#define IDB_OPERATION_LARGE             311
#define IDD_OPERATE                     312
#define IDS_MACHINE_STATUS_RUN          316
#define ID_STATUSBAR_OPERATE_MODE       317
#define IDS_MACHINE_STATUS_STOP         317
#define IDS_MACHINE_STATUS_RESET        318
#define IDS_MACHINE_MODE_AUTO           319
#define IDS_MACHINE_MODE_JOG            320
#define IDS_MACHINE_MODE_REFER          321
#define IDS_MACHINE_MODE_INC            322
#define IDS_MACHINE_MODE_WHEEL          323
#define IDS_MACHINE_MODE_EDIT           324
#define IDS_MACHINE_MODE_MDI            325

#define ID_VIEW_OUTPUTWND               400
#define ID_VIEW_PARAMETERWND            401
#define ID_VIEW_PLCWND                  402
#define ID_VIEW_OPERATERWND             403
#define ID_VIEW_MONITORWND              404
#define IDC_EDIT3                       1009
#define IDC_RICHEDIT21                  1018
#define IDC_TITLE_T                     1020
#define IDC_REALV_T                     1021
#define IDC_TITLE_T2                    1022
#define IDC_SETV_T                      1022
#define ID_MODE_START                   32500
#define ID_BUTTON_MAUTO                 32501
#define ID_BUTTON_MJOG                  32502
#define ID_BUTTON_MMDI                  32503
#define ID_BUTTON_MINC                  32504
#define ID_BUTTON_MREFER                32505
#define ID_BUTTON_MWHEEL                32506
#define ID_MODE_END                     32507
#define IDC_OPERATE_START               32600
#define IDC_BTN_CYCLESTART              32601
#define IDC_BTN_CYCLEINTERUPT           32602
#define IDC_BTN_CYCLERESET              32603
#define IDC_BTN_ROLLBACK                32604
#define ID_BUTTON_XPLUS                 32605
#define ID_BUTTON_XMINUS                32606
#define ID_BUTTON_YPLUS                 32607
#define ID_BUTTON_YMINUS                32608
#define ID_BUTTON_ZPLUS                 32609
#define ID_BUTTON_ZMINUS                32610
#define ID_BUTTON_APLUS                 32611
#define ID_BUTTON_AMINUS                32612
#define ID_BUTTON_BPLUS                 32613
#define ID_BUTTON_BMINUS                32614
#define ID_CHECK_INC_CUT                32615
#define ID_EDIT_INC_VALUE               32616
#define ID_EDIT_RAPID_VALUE             32617
#define ID_COMBO_INCR_VALUE             32618
#define ID_CHECK_INC                    32619
#define ID_CHECK_RAPID                  32620
#define IDC_RICHEDIT_MDI                32621
#define IDC_CHECK_STEPRUN               32622
#define IDC_OPERATE_END                 32622
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_SLIDER_FEEDRATE_OVERRIDE     32796
#define ID_EDIT_FEED                    32799
#define ID_BTN_CONNECT                  32808
#define ID_MACHINE_STATUS               32809
#define IDR_X_POS                       32810
#define IDR_Y_POS                       32811
#define IDR_X_FEED                      32812
#define IDR_Y_FEED                      32813
#define IDR_PROGRESS                    32814
#define IDR_FEEDRATE_VALUE              32816
#define IDR_FEED                        32818
#define IDR_FEEDRATE_SLIDER             32819
#define IDR_PROGRESS_TITLE              32820
#define ID_CHECK5                       32825

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32826
#define _APS_NEXT_CONTROL_VALUE         1022
#define _APS_NEXT_SYMED_VALUE           318
#endif
#endif
